name: Deploy alist-web
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - v2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy to main Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          external_repository: kokeri/alist-web
          publish_branch: dist